In [1]:
import torch
const_dim_tensor = torch.Tensor([1])
print(const_dim_tensor)

tensor([1.])


In [9]:
one_dim_tensor = torch.Tensor([1.1,2.2,3.3])
print(one_dim_tensor)

tensor([1.1000, 2.2000, 3.3000])


In [10]:
two_dim_tensor = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(two_dim_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [14]:
three_dim_tensor = torch.Tensor(
    [[[ 1.,  2.,  3.],
     [ 5.,  6.,  7.]],

    [[ 9., 10., 11.],
     [13., 14., 15.]]]
)
print(three_dim_tensor)

tensor([[[ 1.,  2.,  3.],
         [ 5.,  6.,  7.]],

        [[ 9., 10., 11.],
         [13., 14., 15.]]])
